name: Pytest CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 第一步：检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 第二步：设置 Miniconda
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true            # 自动更新 Conda
          python-version: '3.9'              # 指定 Python 版本
          activate-environment: phishpedia   # 指定要激活的环境

      # 第三步：升级 pip
      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip
        shell: bash

      # 第四步：克隆 Phishpedia 仓库并运行 setup.sh
      - name: Clone Phishpedia repo and run setup.sh
        run: |
          git clone https://github.com/lindsey98/Phishpedia.git
          cd Phishpedia
          chmod +x ./setup.sh
          ./setup.sh
        shell: bash

      # 第五步：安装项目依赖和 pytest
      - name: Install dependencies and pytest
        run: |
          source "${{ steps.setup-miniconda.outputs.conda-prefix }}/etc/profile.d/conda.sh"
          conda activate phishpedia
          pip install -r requirements.txt
          pip install pytest
        shell: bash


      # 步骤 6：运行 Pytest 测试
      - name: Run Pytest
        run: |
          source "${{ steps.setup-miniconda.outputs.conda-prefix }}/etc/profile.d/conda.sh"
          conda activate phishpedia
          pytest tests/test_logo_matching.py
          pytest tests/test_logo_recog.py
          pytest tests/test_phishpedia.py
