name: Pytest CI

# 触发条件：在 push 或 pull request 到 main 分支时运行
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 步骤 1：检出代码
      - name: Checkout repository
        uses: actions/checkout@v3

      # 步骤 2：设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # 根据你的项目需要选择 Python 版本

      # 步骤 3：安装依赖项
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      # 步骤 4：运行 Pytest 测试
      - name: Run Pytest
        run: |
          pytest tests/test_logo_matching.py
          pytest tests/test_logo_recog.py
          pytest tests/test_phishpedia.py
