name: Pytest CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 步骤 1：检出代码
      - name: Checkout repository
        uses: actions/checkout@v3

      # 步骤 2：设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # 根据你的项目需要选择 Python 版本
          
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # 步骤 3：安装依赖项
      - name: Install dependencies
        run: |
          # 升级 pip
          python -m pip install --upgrade pip

          # 克隆 Phishpedia 仓库
          git clone https://github.com/lindsey98/Phishpedia.git

          # 进入 Phishpedia 目录并运行 setup.sh
          cd Phishpedia
          chmod +x ./setup.sh
          ./setup.sh

          # 返回主项目目录
          cd ..

          # 安装 pytest（如果 requirements.txt 中已经包含 pytest，可以省略此行）
          pip install pytest

      # 步骤 4：运行 Pytest 测试
      - name: Run Pytest
        run: |
          pytest tests/test_logo_matching.py
          pytest tests/test_logo_recog.py
          pytest tests/test_phishpedia.py
